// Autogenerated AST node
package com.astra.ses.spell.language.model.ast;

import com.astra.ses.spell.language.model.SimpleNode;

public class commentType extends SimpleNode
{
	public String	id;

	public commentType(String id)
	{
		this.id = id;
	}

	public commentType(String id, SimpleNode parent)
	{
		this(id);
		this.beginLine = parent.beginLine;
		this.beginColumn = parent.beginColumn;
	}

	public String toString()
	{
		StringBuffer sb = new StringBuffer("comment[");
		sb.append("id=");
		sb.append(dumpThis(this.id));
		sb.append("]");
		return sb.toString();
	}

	public Object accept(VisitorIF visitor) throws Exception
	{
		traverse(visitor);
		return null;
	}

	public void traverse(VisitorIF visitor) throws Exception
	{
	}

}
