// Autogenerated AST node
package com.astra.ses.spell.language.model.ast;

import com.astra.ses.spell.language.model.SimpleNode;

public class ImportFrom extends stmtType
{
	public NameTokType	module;
	public aliasType[]	names;
	public int	       level;

	public ImportFrom(NameTokType module, aliasType[] names, int level)
	{
		this.module = module;
		this.names = names;
		this.level = level;
	}

	public ImportFrom(NameTokType module, aliasType[] names, int level,
	        SimpleNode parent)
	{
		this(module, names, level);
		this.beginLine = parent.beginLine;
		this.beginColumn = parent.beginColumn;
	}

	public String toString()
	{
		StringBuffer sb = new StringBuffer("ImportFrom[");
		sb.append("module=");
		sb.append(dumpThis(this.module));
		sb.append(", ");
		sb.append("names=");
		sb.append(dumpThis(this.names));
		sb.append(", ");
		sb.append("level=");
		sb.append(dumpThis(this.level));
		sb.append("]");
		return sb.toString();
	}

	public Object accept(VisitorIF visitor) throws Exception
	{
		return visitor.visitImportFrom(this);
	}

	public void traverse(VisitorIF visitor) throws Exception
	{
		if (module != null) module.accept(visitor);
		if (names != null)
		{
			for (int i = 0; i < names.length; i++)
			{
				if (names[i] != null) names[i].accept(visitor);
			}
		}
	}

}
