// Autogenerated AST node
package com.astra.ses.spell.language.model.ast;

import com.astra.ses.spell.language.model.SimpleNode;

public class Import extends stmtType
{
	public aliasType[]	names;

	public Import(aliasType[] names)
	{
		this.names = names;
	}

	public Import(aliasType[] names, SimpleNode parent)
	{
		this(names);
		this.beginLine = parent.beginLine;
		this.beginColumn = parent.beginColumn;
	}

	public String toString()
	{
		StringBuffer sb = new StringBuffer("Import[");
		sb.append("names=");
		sb.append(dumpThis(this.names));
		sb.append("]");
		return sb.toString();
	}

	public Object accept(VisitorIF visitor) throws Exception
	{
		return visitor.visitImport(this);
	}

	public void traverse(VisitorIF visitor) throws Exception
	{
		if (names != null)
		{
			for (int i = 0; i < names.length; i++)
			{
				if (names[i] != null) names[i].accept(visitor);
			}
		}
	}

}
