// Autogenerated AST node
package com.astra.ses.spell.language.model.ast;

public interface num_typeType
{
	public static final int	     Int	              = 1;
	public static final int	     Long	              = 2;
	public static final int	     Float	              = 3;
	public static final int	     Hex	              = 4;
	public static final int	     Oct	              = 5;
	public static final int	     Comp	              = 6;

	public static final String[]	num_typeTypeNames	= new String[] {
	        "<undef>", "Int", "Long", "Float", "Hex", "Oct", "Comp", };
}
