#!/bin/sh
###################################################################################
## FILE       : pmod
## DATE       : Mar 17, 2011
## PROJECT    : SPELL
## DESCRIPTION: Test script
## -------------------------------------------------------------------------------- 
##
##  Copyright (C) 2008, 2015 SES ENGINEERING, Luxembourg S.A.R.L.
##
##  This file is part of SPELL.
##
## SPELL is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## SPELL is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with SPELL. If not, see <http://www.gnu.org/licenses/>.
##
###################################################################################

export PATH=/home/racc/PYMOD/bin:$PATH
export LD_LIBRARY_PATH=/home/racc/PYMOD/lib:/home/racc/PYMOD/lib/python2.5:/home/racc/PYMOD/lib/python2.5/lib-dynload:$LD_LIBRARY_PATH
export PYTHONPATH=/home/racc/PYMOD:/home/racc/PYMOD/lib:/home/racc/PYMOD/lib/python2.5:/home/racc/PYMOD/lib/python2.5/site-packages
