#!/bin/sh

[[ -z "$1" ]] && echo "Must provide a directory name" && exit -1
[[ ! -d "$1" ]] && echo "Cannot find directory $1" && exit -1

BUILDIR=$1
BUILDIR=`cd $BUILDIR > /dev/null; echo $PWD; cd - > /dev/null`

BASEPATH=`dirname $0`
BASEPATH=`cd $BASEPATH >/dev/null; echo $PWD; cd - >/dev/null`

if [[ -f $BUILDIR/build.date ]]
then
	find $BUILDIR -name "*.py" -cnewer $BUILDIR/build.date -exec $BASEPATH/py-compile '{}' \; | grep -v compiling | uniq
else
	find $BUILDIR -name "*.py" -exec $BASEPATH/py-compile '{}' \; | grep -v compiling  | uniq
fi
touch $BUILDIR/build.date

