package com.astra.ses.spell.language.common;

import com.astra.ses.spell.language.ParseException;
import com.astra.ses.spell.language.model.SimpleNode;

/**
 * Interface for the grammar used.
 * 
 */
public interface IGrammar
{

	void enable_tracing();

	public static Object	parseLock	= new Object();

	/**
	 * Important: code that calls this function must be synchronized with the
	 * parseLock object in this interface. This is needed because there are
	 * optimizations within the parser that require it to be accessed
	 * sequentially.
	 * 
	 * (optimization: openNode in the tree builder)
	 * 
	 * @return the tree structure generated by parsing the file.
	 * 
	 * @throws ParseException
	 */
	SimpleNode file_input() throws ParseException;

}
