/* Generated By:JJTree: Do not edit this line. Node.java */

package com.astra.ses.spell.language.model;

/* All AST nodes must implement this interface.  It provides basic
 machinery for constructing the parent and child relationships
 between nodes. */

public interface Node
{

}
