/* Generated By:JavaCC: Do not edit this line. JJTSpellGrammarState.java Version 5.0 */
package com.astra.ses.spell.language.grammar;

import com.astra.ses.spell.language.common.AbstractJJTGrammarState;
import com.astra.ses.spell.language.common.ITreeBuilder;

public class JJTSpellGrammarState extends AbstractJJTGrammarState
{

	@Override
	protected ITreeBuilder createBuilder()
	{
		return new TreeBuilder(this);
	}

}
